# 1.2.1 Пример

Создать массив 5x2. Создать массив 5x2. Вывести все значения массива, значение элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля.

In [1]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


# 1.2.2 Пример

Пример. Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

In [ ]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


# 1.2.3 Пример

Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение.

In [ ]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.002187843370514475 0.9793758784689879 0.4942594338594747


# 1.2.4 Пример

Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами.

In [ ]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# 1.2.5 Пример

Выяснить результат следующих выражений:

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

0.3 == 3 * 0.1

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


# 1.2.6 Пример

Отсортировать массив.

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


# 1.3.1 Задание

Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [9]:
import numpy as np
arr = np.fromfunction(lambda i, j: (i + j) % 2, (8, 8), dtype=int)
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 1.3.2 Задание

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange.

In [11]:
import numpy as np

arr = np.array([np.arange(0, 5) for i in range(5)])
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# 1.3.3 Задание

Создать массив 3x3x3 со случайными значениями.


In [13]:
import numpy as np

arr = np.random.random((3, 3, 3))
print(arr)

[[[0.38539651 0.30685303 0.71525249]
  [0.91691375 0.86665959 0.67253269]
  [0.41463293 0.58032713 0.84148275]]

 [[0.98129308 0.75684246 0.42450276]
  [0.84041351 0.9578214  0.94915307]
  [0.89959998 0.74767719 0.42235142]]

 [[0.84485885 0.4060887  0.33879539]
  [0.08410605 0.47269654 0.04996834]
  [0.11963414 0.15617422 0.86611713]]]


# 1.3.4 Задание


Создать матрицу с 0 внутри, и 1 на границах.

In [16]:
import numpy as np
n = 10
m = 10
arr = np.ones((10, 10), dtype=int)
arr[1:9, 1:9] = 0
print(arr)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


# 1.3.5 Задание

Создайте массив и отсортируйте его по убыванию.

In [19]:
import numpy as np
arr = np.random.random(10)
arr = -np.sort(-arr)
print(arr)

[0.91998458 0.90801736 0.8508962  0.71853853 0.56502345 0.26329109
 0.16739246 0.13065175 0.06678439 0.02652314]


# 1.3.6 Задание


Создайте матрицу, выведите ее форму, размер и размерность

In [23]:
import numpy as np
a = np.arange(1, 5).reshape((2, 2))
print(a.shape, a.size, a.ndim)

(2, 2) 4 2


# 2.2.1 Пример

Создать Series из списка Python, словаря Python, и массива Numpy (установить буквенные метки для последнего). 

In [28]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


# 2.2.2 Пример

Дано два Series. Напечатать их первые элементы и все элементы после третьего (во втором фрейме).

In [29]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


# 2.2.3 Пример

Создайте новый фрейм данных.

In [30]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

# 2.2.4 Пример

Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [31]:
# Создать URL-адрес
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
# Загрузить данные
dataframe = pd.read_csv(url)
# Показать пять строк
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

# 2.2.5 Пример

Пронализировать характеристики фрейма данных.

In [32]:
dataframe.head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [33]:
dataframe.tail(3)

Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0

In [34]:
dataframe.shape

(1313, 6)

In [35]:
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

# 2.2.6 Пример

Выберите индивидуальные данные или срезы фрейма данных.

In [36]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

# 2.2.7 Пример

Требуется отобрать строки фрейма данных на основе некоторого
условия. Необходимо сформировать новый фрейм данных из пассажиров первого класса.

In [37]:
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

# 2.3.1 Задание

Найдите евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу

In [40]:
import pandas as pd


a = pd.Series([3, 5])
b = pd.Series([7, 4])

print(sum((a - b) ** 2) ** 0.5)


4.123105625617661


# 2.3.2 Задание


Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных.

In [41]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/baby_names_2000.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

year     name gender  count
0  2000    Emily      F  25956
1  2000   Hannah      F  23082
2  2000  Madison      F  19968
3  2000   Ashley      F  17997
4  2000    Sarah      F  17702

# 2.3.3 Задание

Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7.

In [42]:
dataframe.head(2)

year    name gender  count
0  2000   Emily      F  25956
1  2000  Hannah      F  23082

In [43]:
dataframe.tail(3)

year   name gender  count
624233  2018  Zyrie      M      5
624234  2018  Zyron      M      5
624235  2018  Zzyzx      M      5

In [44]:
print(dataframe.shape)

(624236, 4)


In [45]:
dataframe.describe()

year          count
count  624236.000000  624236.000000
mean     2009.115961     113.971929
std         5.383550     754.696900
min      2000.000000       5.000000
25%      2005.000000       7.000000
50%      2009.000000      11.000000
75%      2014.000000      29.000000
max      2018.000000   34477.000000

In [46]:
dataframe.iloc[2:6]

year     name gender  count
2  2000  Madison      F  19968
3  2000   Ashley      F  17997
4  2000    Sarah      F  17702
5  2000   Alexis      F  17629

In [47]:
dataframe[dataframe['gender'] == 'F'].head(2)

year    name gender  count
0  2000   Emily      F  25956
1  2000  Hannah      F  23082

# 3.2.1 Пример

Прошкалируйте числовой признак в диапазон между двумя значениями.


In [ ]:
# Загрузить библиотеки
import numpy as np
from sklearn import preprocessing

# Создать признак
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
# Создать шкалировщик
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))

# Прошкалировать признак
scaled_feature = minmax_scale.fit_transform(feature)

# Показать прошкалированный признак
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

# 3.2.2 Пример

Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное  отклонение 1.

In [ ]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
# Создать шкалировщик
scaler = preprocessing.StandardScaler()
# Преобразовать признак
standadized = scaler.fit_transform(x)
# Показать признак
standadized
print("Среднее:", round(standadized.mean()))
print("Стандартное отклонение:", standadized.std())

Среднее: 0
Стандартное отклонение: 1.0


# 3.2.3 Пример

Дан фрейм данных

dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
 
'B':[103.02,107.26,110.35,114.23,114.68],

'C':['big','small','big','small','small']})

Необходимо масштабировать его числовые столбцы.

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                       'B':[103.02,107.26,110.35,114.23,114.68],
                       'C':['big','small','big','small','small']})

dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

# 3.3.2 Задание


Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.

Необходимо выполнить нормализацию первого числового признака (`sepal_length_cm`) с использованием минимаксного преобразования, а второго (`sepal_width_cm`) с задействованием z-масштабирования.

In [48]:
from sklearn import preprocessing

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)

scaler1 = preprocessing.MinMaxScaler()
scaler2 = preprocessing.StandardScaler()
dataframe[['sepal_length_cm']] = scaler1.fit_transform(dataframe[['sepal_length_cm']])
dataframe[['sepal_width_cm']] = scaler2.fit_transform(dataframe[['sepal_width_cm']])

dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]