# 1.3.1 Задание

Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
import numpy as np
arr = np.fromfunction(lambda i, j: (i + j) % 2, (8, 8), dtype=int)
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 1.3.2 Задание

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange.

In [ ]:
import numpy as np

arr = np.array([np.arange(0, 5) for _ in range(5)])
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# 1.3.3 Задание

Создать массив 3x3x3 со случайными значениями.


In [ ]:
import numpy as np

arr = np.random.random((3, 3, 3))
print(arr)

[[[0.19645526 0.89335863 0.79461325]
  [0.66141762 0.34307593 0.47466567]
  [0.3919623  0.61044335 0.49656643]]

 [[0.74896451 0.2144444  0.33471207]
  [0.72672203 0.56212592 0.26123182]
  [0.84649095 0.560324   0.87890632]]

 [[0.83598744 0.0490868  0.31255472]
  [0.19184223 0.27985259 0.85823724]
  [0.26096626 0.86663426 0.77666445]]]


# 1.3.4 Задание


Создать матрицу с 0 внутри, и 1 на границах.

In [ ]:
import numpy as np
n = 10
m = 10
arr = np.ones((n, m), dtype=int)
arr[1:n-1, 1:m-1] = 0
print(arr)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


# 1.3.5 Задание

Создайте массив и отсортируйте его по убыванию.

In [ ]:
import numpy as np

n = 10
arr = np.random.random(n)
arr = -np.sort(-arr)
print(arr)

[0.94076083 0.86051002 0.85133816 0.84280757 0.83493334 0.73029939
 0.59826431 0.52472054 0.20913221 0.17229839]


# 1.3.6 Задание


Создайте матрицу, выведите ее форму, размер и размерность

In [ ]:
import numpy as np

matrix = np.matrix(np.arange(1, 10).reshape((3, 3)))

print(matrix.shape, matrix.size, matrix.ndim)

(3, 3) 9 2


# 2.3.1 Задание

Найдите евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу

In [ ]:
import pandas as pd


a = pd.Series([3, 5])
b = pd.Series([7, 4])

print(sum((a - b) ** 2) ** 0.5)


4.123105625617661


# 2.3.2 Задание


Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных.

In [ ]:
url = 'https://raw.githubusercontent.com/chrisalbon/sim_data/master/sales.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

Name                         Country                Company  \
0    Brenden Cote        Central African Republic            Metus Corp.   
1    Justina Reed                         Namibia           Lobortis Ltd   
2   Daquan Vinson  Svalbard and Jan Mayen Islands        A Mi Consulting   
3  Connor Shelton                            Niue  Parturient Consulting   
4    Drew Carlson                         Mayotte    Interdum Associates   

           Date  Sales  
0  Feb 17, 2018  67044  
1  Apr 27, 2017  89517  
2  Aug 14, 2016  62705  
3  Feb 13, 2017  12675  
4  Sep 26, 2017  86670

# 2.3.3 Задание

In [ ]:
dataframe.head(2)

Name                   Country       Company          Date  Sales
0  Brenden Cote  Central African Republic   Metus Corp.  Feb 17, 2018  67044
1  Justina Reed                   Namibia  Lobortis Ltd  Apr 27, 2017  89517

In [ ]:
dataframe.tail(3)

Name      Country             Company          Date  Sales
97  Libby Lindsey        Qatar     Convallis Corp.   Nov 5, 2016  10583
98   Cody Langley  Isle of Man  Est Mollis Company   Oct 9, 2017  98167
99   Colt Schultz   Guadeloupe  Dolor Nonummy Inc.  Nov 18, 2017  39988

In [ ]:
print(dataframe.shape)

(100, 5)


In [ ]:
dataframe.describe()

Sales
count    100.000000
mean   51892.470000
std    29707.005083
min       59.000000
25%    29415.750000
50%    48845.500000
75%    77878.000000
max    99880.000000

In [ ]:
dataframe.iloc[2:6]

Name                         Country  \
2   Daquan Vinson  Svalbard and Jan Mayen Islands   
3  Connor Shelton                            Niue   
4    Drew Carlson                         Mayotte   
5   Yoshio Curtis                    Saint Martin   

                       Company          Date  Sales  
2              A Mi Consulting  Aug 14, 2016  62705  
3        Parturient Consulting  Feb 13, 2017  12675  
4          Interdum Associates  Sep 26, 2017  86670  
5  Ultrices Sit Amet Institute   Apr 2, 2017  95955

In [ ]:
dataframe[dataframe['Country'] == 'China'].head(2)

Name Country                 Company          Date  Sales
22  Piper Daugherty   China              Eu Limited   Jun 7, 2016  56331
48      Farrah Ward   China  Cursus Et Eros Limited  Jul 31, 2016  77784

# 3.3.2 Задание

Необходимо выполнить нормализацию первого числового признака (`sepal_length_cm`) с использованием минимаксного преобразования, а второго (`sepal_width_cm`) с задействованием z-масштабирования.

In [ ]:
from sklearn import preprocessing

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)

scaler1 = preprocessing.MinMaxScaler()
scaler2 = preprocessing.StandardScaler()
dataframe[['sepal_length_cm']] = scaler1.fit_transform(dataframe[['sepal_length_cm']])
dataframe[['sepal_width_cm']] = scaler2.fit_transform(dataframe[['sepal_width_cm']])

dataframe

sepal_width_cm   -6.631732e-16
dtype: float64


sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]